In [1]:
import os
import pandas as pd
os.chdir(os.getcwd() + "/../")

In [2]:
from data_cofig import data_config

#### 1） Read Train Data

In [3]:
train_df = pd.read_csv(data_config.train_data_path,sep="\t")

In [4]:
train_df.head()

quality                                          #1 string  \
0        1  amrozi accused his brother whom he called the ...   
1        0  yucaipa owned dominicks before selling the cha...   
2        1  they had published an advertisement on the int...   
3        0  around 0335 gmt tab shares were up 19 cents or...   
4        1  the stock rose $2.11 or about 11 percent to cl...   

                                           #2 string  
0  referring to him as only the witness amrozi ac...  
1  yucaipa bought dominicks in 1995 for $693 mill...  
2  on june 10 the ships owners had published an a...  
3  tab shares jumped 20 cents or 4.6% to set a re...  
4  pg&e corp. shares jumped $1.63 or 8 percent to...

In [5]:
text_1 = train_df['#1 string']

text_2 = train_df['#2 string']

#### 2） Preprocess

In [30]:
from utils import clean_text,remove_stopwords,tokenize
from corpus import read_word2vec

In [31]:
text_list = list(train_df['#1 string'])[:10]

In [11]:
text = "amrozi accused his brother whom he called th"

In [15]:
from text_process import TextPreprocessor

In [16]:
pipelines = [clean_text,remove_stopwords,tokenize]

In [35]:
text_preprocessor = TextPreprocessor(pipelines)

In [36]:
text_list = text_preprocessor.transform(text_list)

In [38]:
import tensorflow as tf

In [39]:
default_config = {"num_words": None,
                  'filters': '',
                  "lower": True,
                  'split': ' ',
                  'char_level': False,
                  'oov_token': None,
                  'document_count': 0}


In [40]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(**default_config)

In [43]:
# text_list

In [45]:
import numpy as np

In [49]:
tf.keras.preprocessing.sequence.pad_sequences(text_list, padding='post',dtype=np.object,value = 'EOS',maxlen=2)

array([['distorting', 'evidence'],
       ['5', 'billion'],
       ['sale', 'added'],
       ['4', '57'],
       ['stock', 'exchange'],
       ['year', 'earlier'],
       ['15', 'friday'],
       ['supreme', 'court'],
       ['ago', 'period'],
       ['growth', 'strategy']], dtype=object)

In [48]:
tf.keras.preprocessing.sequence.pad_sequences(text_list, padding='post',dtype=np.object,value = 'EOS',maxlen=None)

array([['amrozi', 'accused', 'brother', 'called', 'witness',
        'deliberately', 'distorting', 'evidence', 'EOS', 'EOS', 'EOS',
        'EOS', 'EOS', 'EOS', 'EOS', 'EOS', 'EOS'],
       ['yucaipa', 'owned', 'dominicks', 'selling', 'chain', 'safeway',
        '1998', '2', '5', 'billion', 'EOS', 'EOS', 'EOS', 'EOS', 'EOS',
        'EOS', 'EOS'],
       ['published', 'advertisement', 'internet', 'june', '10',
        'offering', 'cargo', 'sale', 'added', 'EOS', 'EOS', 'EOS', 'EOS',
        'EOS', 'EOS', 'EOS', 'EOS'],
       ['around', '0335', 'gmt', 'tab', 'shares', '19', 'cents', '4',
        '4', '4', '56', 'earlier', 'set', 'record', 'high', '4', '57'],
       ['stock', 'rose', '2', '11', '11', 'percent', 'close', 'friday',
        '21', '51', 'new', 'york', 'stock', 'exchange', 'EOS', 'EOS',
        'EOS'],
       ['revenue', 'first', 'quarter', 'year', 'dropped', '15',
        'percent', 'period', 'year', 'earlier', 'EOS', 'EOS', 'EOS',
        'EOS', 'EOS', 'EOS', 'EOS'],
     

In [20]:
# text_list

### 3) Update Word2Vec

In [15]:
word2vec_matrix = read_word2vec()

0it [00:00, ?it/s]

reading the word2vec matrix


516783it [01:24, 6125.04it/s]

Reading Completed !


In [20]:
import numpy as np

In [28]:
word2vec_matrix['love'].reshape(1,-1).shape

(1, 300)

In [ ]:
word2vec_matrix['love'].reshape(1,-1).shape

In [30]:
np.dot(word2vec_matrix['love'].reshape(1,-1),word2vec_matrix['love'].reshape(-1,1))

array([[1.0000827]], dtype=float32)

In [33]:
def dot_product(vec_1,vec_2):
    return np.dot(vec_1.reshape(1,-1),vec_2.reshape(-1,1))

In [43]:
vec_1 = np.random.uniform(-0.1,0.1,300)

In [44]:
vec_2 = np.random.uniform(-0.1,0.1,300)

In [45]:
dot_product(vec_1,vec_2)

array([[0.04197309]])

In [46]:
# word2vec_matrix['love']

In [ ]:
def update_word2vec_matrix(words_list,word2vec_matrix):
    

In [16]:
import tensorflow as tf

In [17]:
default_config = {"num_words": None,
                  'filters': '',
                  "lower": True,
                  'split': ' ',
                  'char_level': False,
                  'oov_token': None,
                  'document_count': 0}

In [18]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(**default_config)

In [19]:
tokenizer.fit_on_texts(text_list)

In [20]:
# tensor = tokenizer.texts_to_sequences(text_list)

In [47]:
# tensor

In [38]:
tf.keras.preprocessing.sequence.pad_sequences(tensor, padding='post')

array([[12, 13, 14, 15, 16, 17, 18, 19,  0,  0,  0,  0,  0,  0,  0,  0,
         0],
       [20, 21, 22, 23, 24, 25, 26,  2, 27, 28,  0,  0,  0,  0,  0,  0,
         0],
       [29, 30, 31, 32, 33, 34, 35, 36, 37,  0,  0,  0,  0,  0,  0,  0,
         0],
       [38, 39, 40, 41, 42, 43,  5,  1,  1,  1, 44,  6, 45, 46, 47,  1,
        48],
       [ 7, 49,  2,  8,  8,  3, 50,  9, 51, 52, 53, 54,  7, 55,  0,  0,
         0],
       [56, 57, 58,  4, 59, 10,  3, 11,  4,  6,  0,  0,  0,  0,  0,  0,
         0],
       [60, 61, 62, 63, 64, 65,  2,  3, 66, 67, 10,  9,  0,  0,  0,  0,
         0],
       [68, 69, 70, 71, 72, 73,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0],
       [74, 75, 76, 77, 78,  5, 79, 80,  4, 81, 11,  0,  0,  0,  0,  0,
         0],
       [82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,  0,  0,  0,  0,  0,
         0]])

In [37]:
tensor

[[12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 2, 27, 28],
 [29, 30, 31, 32, 33, 34, 35, 36, 37],
 [38, 39, 40, 41, 42, 43, 5, 1, 1, 1, 44, 6, 45, 46, 47, 1, 48],
 [7, 49, 2, 8, 8, 3, 50, 9, 51, 52, 53, 54, 7, 55],
 [56, 57, 58, 4, 59, 10, 3, 11, 4, 6],
 [60, 61, 62, 63, 64, 65, 2, 3, 66, 67, 10, 9],
 [68, 69, 70, 71, 72, 73],
 [74, 75, 76, 77, 78, 5, 79, 80, 4, 81, 11],
 [82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92]]

In [19]:
word2vec_matrix = read_word2vec()

676it [00:00, 6710.93it/s]

reading the word2vec matrix


516783it [01:02, 8297.48it/s]

Reading Completed !
